---

- name: Create easyrsa pki directory
  file:
    name: "{{ easyrsa_pki_dir }}"
    mode: 700
    state: directory

- name: Initiate PKI
  command: easyrsa --batch init-pki
  args:
    creates: "{{ easyrsa_pki_dir }}/private"
  when: not easyrsa_replace_pki | bool

- name: Replace PKI
  command: easyrsa init-pki
  when: easyrsa_replace_pki | bool
  changed_when: true

- name: Upload vars file
  template:
    src: vars.j2
    dest: "{{ easyrsa_pki_dir }}/vars"
    mode: 0o755

- name: Create CA
  command: easyrsa build-ca nopass
  register: _result
  failed_when:
    - _result is failed
    - _result.stderr | default(_result.stdout, true)
      is not search('you already seem to have one set up')
  changed_when: _result is not failed
